name: Build assets
on: push
jobs:
  compile-uswds-assets:
    name: Compile USWDS assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Copy project assets
        run: npx gulp copyAssets
      - name: Compile project SCSS
        run: npx gulp compile
      - name: Upload project assets
        uses: actions/upload-artifact@v3
        with:
          name: uswds-assets
          path: assets/
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: compile-uswds-assets
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: uswds-assets
      - name: Zip release build
        uses: thedoctor0/zip-release@master
        with:
          filename: assets-v${{ github.run_number }}.zip
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-releas.outputs.upload_url }}
          asset_path: assets-v${{ github.run_number }}.zip
          asset_name: assets-v${{ github.run_number }}.zip
          asset_content_type: application/zip
